name = "TillyCraft Modpack"
author = "TychoVI"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56077fc8c664875c76bc825508378811f613b4a7045815fa405b90ffe615441f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
